name: compose-redis-stack

services:
  redis_stack:
    container_name: redis_stack
    image: redis/redis-stack:latest
    restart: on-failure:3
    environment:
      REDIS_ARGS: '--requirepass password --user root on >password ~* allcommands --user default off nopass nocommands'
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./tmp/redis_data:/data

